local Pass = {
	Id = 3488013162;
	HasPass = false;
	Progress = 0;
	Tier1 = {
		Paid = false;
		Claimed = false;
		Needed = 100;
		Reward = {
			Type = "Perk";
			Prize = "HappyFeet";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier2 = {
		Paid = false;
		Claimed = false;
		Needed = 200;
		Reward = {
			Type = "Perk";
			Prize = "Cryo Retaliation";
			Character = "Killer" --orr Trapper/Wraith...
		};
	};
	Tier3 = {
		Paid = false;
		Claimed = false;
		Needed = 300;
		Reward = {
			Type = "Perk";
			Prize = "Cold Comfort";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier4 = {
		Paid = false;
		Claimed = false;
		Needed = 400;
		Reward = {
			Type = "Perk";
			Prize = "Shattered Momentum";
			Character = "Killer" --orr Trapper/Wraith...
		};
	};
	Tier5 = {
		Paid = true;
		Claimed = false;
		Needed = 500;
		Reward = {
			Type = "Cosmetic";
			Prize = "Present Bandit";
			Character = "Ninja" --orr Trapper/Wraith...
		};
	};
	Tier6 = {
		Paid = true;
		Claimed = false;
		Needed = 600;
		Reward = {
			Type = "Cosmetic";
			Prize = "Sbevemas";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier7 = {
		Paid = true;
		Claimed = false;
		Needed = 700;
		Reward = {
			Type = "Cosmetic";
			Prize = "Gingerbread Soulseeker";
			Character = "Reaper" --orr Trapper/Wraith...
		};
	};
	Tier8 = {
		Paid = true;
		Claimed = false;
		Needed = 800;
		Reward = {
			Type = "Cosmetic";
			Prize = "Good old days";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier9 = {
		Paid = true;
		Claimed = false;
		Needed = 900;
		Reward = {
			Type = "Cosmetic";
			Prize = "Snowman";
			Character = "Wraith" --orr Trapper/Wraith...
		};
	};
	Tier10 = {
		Paid = true;
		Claimed = false;
		Needed = 999;
		Reward = {
			Type = "Cosmetic";
			Prize = "pumpkin";
			Character = "Stalker" --orr Trapper/Wraith...
		};
	};
	
}

return Pass
