local Pass = {
	Id = 3420127758;
	HasPass = false;
	Progress = 0;
	Tier1 = {
		Paid = false;
		Claimed = false;
		Needed = 67;
		Reward = {
			Type = "Cosmetic";
			Prize = "Sbeve";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier2 = {
		Paid = false;
		Claimed = false;
		Needed = 133;
		Reward = {
			Type = "Cosmetic";
			Prize = "Knight";
			Character = "Hillbilly" --orr Trapper/Wraith...
		};
	};
	Tier3 = {
		Paid = true;
		Claimed = false;
		Needed = 199;
		Reward = {
			Type = "Cosmetic";
			Prize = "Golden Sbeve";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier4 = {
		Paid = false;
		Claimed = false;
		Needed = 265;
		Reward = {
			Type = "Cosmetic";
			Prize = "Chef of Chefs";
			Character = "Architect" --orr Trapper/Wraith...
		};
	};
	Tier5 = {
		Paid = false;
		Claimed = false;
		Needed = 331;
		Reward = {
			Type = "Cosmetic";
			Prize = "Bunny";
			Character = "Trapper" --orr Trapper/Wraith...
		};
	};
	Tier6 = {
		Paid = true;
		Claimed = false;
		Needed = 397;
		Reward = {
			Type = "Cosmetic";
			Prize = "Golden Streetwise";
			Character = "Hillbilly" --orr Trapper/Wraith...
		};
	};
	Tier7 = {
		Paid = false;
		Claimed = false;
		Needed = 463;
		Reward = {
			Type = "Cosmetic";
			Prize = "Cold Hearted";
			Character = "Trapper" --orr Trapper/Wraith...
		};
	};
	Tier8 = {
		Paid = false;
		Claimed = false;
		Needed = 529;
		Reward = {
			Type = "Cosmetic";
			Prize = "Fireworker";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier9 = {
		Paid = true;
		Claimed = false;
		Needed = 595;
		Reward = {
			Type = "Cosmetic";
			Prize = "Vanity";
			Character = "Psychopath" --orr Trapper/Wraith...
		};
	};
	Tier10 = {
		Paid = false;
		Claimed = false;
		Needed = 661;
		Reward = {
			Type = "Cosmetic";
			Prize = "Streetwise";
			Character = "Hillbilly" --orr Trapper/Wraith...
		};
	};
	Tier11 = {
		Paid = false;
		Claimed = false;
		Needed = 727;
		Reward = {
			Type = "Cosmetic";
			Prize = "TV Time Cosplayer";
			Character = "Architect" --orr Trapper/Wraith...
		};
	};
	Tier12 = {
		Paid = true;
		Claimed = false;
		Needed = 793;
		Reward = {
			Type = "Cosmetic";
			Prize = "Evolved Fireworker";
			Character = "Survivor" --orr Trapper/Wraith...
		};
	};
	Tier13 = {
		Paid = false;
		Claimed = false;
		Needed = 859;
		Reward = {
			Type = "Cosmetic";
			Prize = "Sleepy Time";
			Character = "Huntress" --orr Trapper/Wraith...
		};
	};
	Tier14 = {
		Paid = false;
		Claimed = false;
		Needed = 925;
		Reward = {
			Type = "Cosmetic";
			Prize = "Boundary Weaver";
			Character = "Phantasm" --orr Trapper/Wraith...
		};
	};
	Tier15 = {
		Paid = true;
		Claimed = false;
		Needed = 1000;
		Reward = {
			Type = "Cosmetic";
			Prize = "Dark Lord";
			Character = "Reaper" --orr Trapper/Wraith...
		};
	};
	
}

return Pass
