local Maps = {
	'RANDOM',
	'Test Map',
	'Map Testing 1',
	'Map Testing 2',
	'Haddonfield',
	'Dead Dawg Saloon',
	'Blood Lodge',
	"Azarov's Resting Place",
	"Wreckers' Yard",
	'Coal Tower',
	'Fractured Space',
	--'The Beginning',
	--'Dire Abyss',
	"Johnson's Heartbeat",
	'The Abomination',
	'Unbridled Force',
	--'No Red Paint',
	'Infinite Cornrows',
	'Fractured Cowshed',
	'Rotten Fields',
	'Rancid Abattoir',
	'The Forest',
	'Nightmare Forest',
	'Camping Woods',
	'Classic',
	'Retro Castle',
	--"DeadWood Haven",
	"Stratinn's Cellar",
	"Hunting Grounds",
	--"Unit Disposal",
	"Blighted Grove",
	'Sanctum of Wrath',
	'Haunted Village',
	'Grace Abounds Church',
	'The Ruins',
	"The Library",
	"Ormond Port Blox",
	'The Yard',
	'Hawkins Laboratory',
	'Charon Co. Ferry Tours',
	'Flower Garden',
	'Dead Tree Sanctuary',
	'Dead Sands',
	'Crucifixion Woods',
	"Mountain Ski Resort",
	



	-- Winter Maps --
	--'Winter Haddonfield',
	'Winter Tower',
	'Winter Lodge',
	'Fractured Winter',
	"Snowy Classic",
	"Winter Cowshed",
	"Winter Fields",
	--"Winter Forest",
	--"Sanctum of Wrath",

	-- Winter Fan Maps --
	"Winter Nightmare Forest",
	--"Stratinn's Icy Cellar",
	'Winter Camping Woods',


	--Halloween Maps--
	--"Fall Nightmare Forest",
	--"Fall Classic",
	--"Fall Stratinns Cellar",
	--"Fall Grace Abounds Church",
	--"Fall Haunted Village",
	--"Fall Fractured Space",
	--'Fall Coal Tower',
	--'Fall Dead Dawg Saloon',
	--"Fall Fractured Cowshed",
	--"Fall Forest",
	--"Fall Haddonfield",
	--"Fall Rotten Fields", 
	--"Fall Echoing Ruins",
	--"Fall Sanctum of Wrath",
	--"Fall Blood Lodge",
	
	
	
}

return Maps
