local Note = {
	Content = [[

JOLLY UPDATE

Added new pass that includes:
6 new skins (paid)
Present Bandit (Ninja)
Sbevemas (Survivor)
Gingerbread Soulseeker (Reaper)
Good old days (Survivor)
Snowman (Wraith)
pumpkin (Stalker)


4 new perks (free) -> If you fail to get the perks through the pass, perks will be released sometime after the event ends

Happy Feet (Survivor):
After being hit, instantly get Exhaustion< and gain 3% Haste for 100 seconds. This perk has a exhaustion cooldown of 300/200/100 seconds.

Cold Comfort (Survivor):
After being chased for 40/35/30 seconds, you unlock the ability to turn a hook into it's icy form. Survivors hooked on icy hooks die 25% slower. The icy effect wears off once the Survivor has been rescued from an icy hook.

Cryo Retaliation (Killer):
Every time a Survivor stuns you with a pallet, you call upon [REDACTED] to slow them down for 0.8/1/1.2 seconds. Perk has a cooldown of 20 seconds between uses.

Shattered Momentum (Killer):
Breaking a pallet grants you a 1% Haste status effect, stacking up to 3/4/5 times for a maximum of 3/4/5% Haste. Downing a Survivor removes all Haste stacks.


Added pages to cosmetics UI in the main menu
Readded Christmas decorations to interactables
Main menu has gotten jollified
There is a new badge which will award you with a new cosmetic for Survivor 😼

Balance Changes

Self Defense

Stun duration: 4s > 5s


Architect

Cancel power animation duration: 3s > 2.7s


Ninja

Speed while aiming: 0.4% > 0.45% (of base speed)

Dash hitbox radius: 1.6 > 1.8

Collision I-frames: 0.35 > 0.45

Animation after using dash: 3.5s > 2.7s 

]],
	
}

return Note
